### PR TITLE
A sample with A* path finding, Tile-map and AABB collision detection(broad phase and narrow phase). 

### PR DESCRIPTION
**Pull request by RickyYCheng**
Files: 
`Tiles.fs` my tilemap solution. 
use both white texture and custom texture. 
already tested in "Tiled". 
see: [Tiled, a map editor program. ](https://www.mapeditor.org/)
also: [my repo. ](https://github.com/RickyYChan/Xelmish/tree/ricky-trial/samples/xelmish-forth)

`Collisions.fs` a queryable collision tree. (BVH Tree, or AABB tree)
not that good, but seems not too slow. 
reference: [box2D](https://box2d.org/files/ErinCatto_DynamicBVH_GDC2019.pdf)
(and an AVL tree tutorial, but I cannot find it)

`Player.fs`: a simple elmish module 

`AStar.fs`: reference the F# A* path-finding code from Chris Pritchard. 
[CP's A* repo](https://github.com/ChrisPritchard/astar-search)
with little changes. 

Some problems: 
The map is 1600px * 900px or 64tiles * 36tiles. 
When the path is too far like the top left to right bottom, the fps will obviously decrease on my laptop. 
(Windows 11, .Net6.0, intel i5-8xxxU). 
(60fps -> 20fps) 

I think the path-finding program should use a priority queue(heap) to make an improvement. 
And I donnot think the priority queue in .net6 is a good idea, since it is not immutable.

### CODE REVIEW

**Comment by RickyYCheng** [comment]
Since I use .net6, and then downgrade to .net 5. 
In `program.fs`
```fs
let init () =

    let rndMap cols rows =
        [| for y = 0 to rows - 1 do
               for x = 0 to cols - 1 do
                   // [0, n) or [0, n - 1].
                   yield Random.Shared.Next(0, 5) |]
```

`System.Random.Shared` won't work.

**Comment by RickyYCheng** [comment]
in astar 
```fs
if List.contains neighbour openSet && tentativeGScore >= Map.find neighbour gScores 
then (openSet, gScores, fScores, cameFrom)
else
    let newOpenSet = if List.contains neighbour openSet then openSet else neighbour::openSet
```
seem that we do `List.contains neighbour openSet` two times.

**Comment by ChrisPritchard** [comment]
Hey, this is awesome, but it fits more as a repo/project on its own I think than as a Xelmish sample. It demonstrates an effective implementation of A* though!

**Comment by RickyYCheng** [comment]
> Hey, this is awesome, but it fits more as a repo/project on its own I think than as a Xelmish sample. It demonstrates an effective implementation of A* though!

Alright!

**Comment by b0wter** [comment]
@RickyYCheng : Is there any chance you still have the example code? I'd really like to take a look at it.

**Comment by RickyYCheng** [comment]
> @RickyYCheng : Is there any chance you still have the example code? I'd really like to take a look at it.

Nope, I've deleted the src in my repo. 
But you can still check them in this PR, just click files changed to see something remained.

**Pull request closed without merging**
